//! Finite skeletal category probe (MVP Probe B).
//!
//! Checks obligations in small finite categories (N≤3 default).
//! Returns UnsupportedFragment if categorical presentation not extractable.

use crate::refute::types::{BoundedList, RefuteLimits, RefuteFragment, TruncationReason};
use crate::refute::probe::{
    ProbeDoctrine, ProbeKey, InterpretationCandidate, InterpretationData, RefuteCheckResult,
};
use crate::refute::slice::RefuteSlice;

/// Finite skeletal category probe.
///
/// **Semantics**:
/// - Domain: objects 0..N-1
/// - Morphisms: generated by slice with explicit composition
/// - Checks: composition, identities, associativity
/// - Returns `UnsupportedFragment` if categorical presentation not extractable
pub struct FiniteCatProbe;

impl FiniteCatProbe {
    pub fn new() -> Self {
        Self
    }
}

impl ProbeDoctrine for FiniteCatProbe {
    fn key(&self) -> ProbeKey {
        ProbeKey {
            id: "finite_cat".to_string(),
            level: 0,
            description: "Finite skeletal category probe: checks composition and identity laws".to_string(),
        }
    }

    fn max_level(&self) -> u8 {
        0 // Level-0 only for MVP
    }

    fn supports_fragment(&self, frag: &RefuteFragment) -> bool {
        matches!(frag, RefuteFragment::CategoricalFinite)
    }

    fn enumerate_interpretations(
        &self,
        _slice: &RefuteSlice,
        limits: &RefuteLimits,
    ) -> BoundedList<InterpretationCandidate> {
        // Enumerate small categories up to max_domain_size
        let max_n = limits.max_domain_size.min(5); // Hard cap at 5
        
        let mut candidates = Vec::new();
        for n in 1..=max_n {
            candidates.push(InterpretationCandidate {
                domain_size: n,
                id: format!("cat_{}", n),
                data: InterpretationData::FiniteCategory {
                    objects: n,
                    morphism_count: 0, // Will be computed from slice
                },
            });
            
            if candidates.len() >= limits.max_interpretations {
                return BoundedList::truncated(
                    candidates,
                    max_n,
                    TruncationReason::MaxResults,
                );
            }
        }
        
        BoundedList::from_vec(candidates)
    }

    fn check(
        &self,
        interp: &InterpretationCandidate,
        slice: &RefuteSlice,
        _limits: &RefuteLimits,
    ) -> RefuteCheckResult {
        // MVP: Return UnsupportedFragment since we don't have categorical
        // presentation extraction yet. This is honest.
        
        // Real implementation would:
        // 1. Extract categorical presentation from slice
        // 2. Generate composition table for N objects
        // 3. Check each obligation against the composition table
        // 4. Return FoundFailure with specific interpretation that fails
        
        RefuteCheckResult::UnsupportedFragment {
            reason: format!(
                "Categorical presentation extraction not yet implemented for domain size {}",
                interp.domain_size
            ),
        }
    }
}

impl Default for FiniteCatProbe {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_finite_cat_probe_key() {
        let probe = FiniteCatProbe::new();
        let key = probe.key();
        assert_eq!(key.id, "finite_cat");
        assert_eq!(key.level, 0);
    }

    #[test]
    fn test_finite_cat_probe_supports_categorical() {
        let probe = FiniteCatProbe::new();
        assert!(probe.supports_fragment(&RefuteFragment::CategoricalFinite));
        assert!(!probe.supports_fragment(&RefuteFragment::Equational));
    }

    #[test]
    fn test_enumerate_respects_limits() {
        use crate::refute::types::{StableAnchor, AnchorKind};
        
        let probe = FiniteCatProbe::new();
        let slice = RefuteSlice {
            anchor: StableAnchor::test(AnchorKind::Goal, "file:///test.ml", 0),
            obligations: vec![],
            coherence_obligations: vec![],
            rules: BoundedList::empty(),
            defs: BoundedList::empty(),
            coherence_level: 0,
        };
        
        let limits = RefuteLimits {
            max_domain_size: 3,
            ..Default::default()
        };
        
        let interps = probe.enumerate_interpretations(&slice, &limits);
        assert_eq!(interps.items.len(), 3);
        assert!(!interps.truncated);
    }
}
