//! This module contains the core data models and a minimal runner for the
//! Mac Lane tactics layer. It serves as a starter slice implementation
//! based on the `TACTICS_LAYER_SPEC.md`, reusing existing types from the codebase.

use crate::document::ByteSpan; // Re-using existing ByteSpan
use crate::refute::types::{BoundedList, StableAnchor}; // Re-using existing types
use codeswitch::fingerprint::HashValue; // Re-using existing HashValue
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

// --- SemanticPatch Data Model ---

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SemanticPatch {
    // Unique identifier for this patch, derived deterministically from its content.
    // E.g., SHA256 of canonical serialization.
    pub id: HashValue,
    // Protocol version for forward/backward compatibility
    pub version: u32,
    // The kind of semantic transformation applied (e.g., "IntroBinding", "ApplyLemma", "FillHole")
    pub kind: PatchKind,
    // The target in the document (e.g., a specific goal, hole, or span).
    pub target_anchor: StableAnchor,
    // List of semantic diffs, ordered deterministically.
    pub changes: BoundedList<SemanticChange>,
    // Optional: new subgoals generated by the tactic, ordered deterministically.
    pub new_subgoals: BoundedList<Goal>,
    // Optional: UI metadata for LSP, not affecting semantic content
    pub ui_metadata: Option<UIMetadata>,
    // Proof of soundness if applicable and already checked (e.g., a hash of a certified proof term).
    pub soundness_proof_artifact: Option<HashValue>,
}

impl SemanticPatch {
    /// Computes a deterministic hash for the patch by canonical serialization.
    /// Uses `codeswitch::fingerprint::HashValue::hash_with_domain`.
    pub fn compute_id(&self) -> HashValue {
        let mut patch_clone = self.clone();
        patch_clone.id = HashValue::zero(); // Clear ID to prevent circular dependency in hash
        let serialized =
            serde_json::to_string(&patch_clone).expect("Failed to serialize patch for hashing");
        HashValue::hash_with_domain(b"EDGELORD_SEMANTIC_PATCH_V1", serialized.as_bytes())
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PatchKind {
    IntroBinding {
        name: String,
        type_expr: String,
    },
    FillHole {
        hole_id: String,
        term: String, // term is a Mac Lane surface form string
    },
    ApplyRule {
        rule_id: String,
        instantiation: BTreeMap<String, String>, // Rule name and instantiation of metavars
    },
    Rewrite {
        rule_id: String,
        direction: RewriteDirection,
        target_span: ByteSpan,
    },
    // Add other tactic-specific patch kinds as needed
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SemanticChange {
    InsertForm {
        parent_anchor: StableAnchor,
        position: InsertPosition,
        new_form_text: String, // Mac Lane surface form text to insert
    },
    DeleteForm {
        target_anchor: StableAnchor,
    },
    UpdateForm {
        target_anchor: StableAnchor,
        new_form_text: String, // Mac Lane surface form text to update with
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RewriteDirection {
    LeftToRight,
    RightToLeft,
    Bidirectional,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum InsertPosition {
    Prepend,
    Append,
    Before(StableAnchor),
    After(StableAnchor),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Goal {
    pub id: String, // Deterministic ID for the goal
    pub anchor: StableAnchor, // Location in the document that implies this goal
    pub statement: String, // Mac Lane surface form of the goal statement
    pub context: BoundedList<ContextItem>, // Relevant context items
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ContextItem {
    Binding { name: String, type_expr: String },
    // ... other context items like hypotheses, definitions
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct UIMetadata {
    pub title: String,
    pub description: Option<String>,
    pub icon: Option<String>,
}

// --- Tactic Input Data Model ---

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TacticInput {
    pub current_proof_state: ProofState,
    pub target_hole_id: Option<String>,
    pub target_goal_id: Option<String>,
    pub additional_args: BTreeMap<String, String>,
    pub current_document_snapshot_hash: HashValue,
    pub current_compile_options_hash: HashValue,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProofState {
    pub goals: BoundedList<Goal>,
    pub holes: BoundedList<Hole>,
    pub definitions_in_scope: BoundedList<StableAnchor>,
    pub rules_in_scope: BoundedList<StableAnchor>,
    pub current_focus_anchor: StableAnchor,
    pub workspace_snapshot_hash: HashValue,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Hole {
    pub id: String,
    pub anchor: StableAnchor,
    pub expected_type: Option<String>, // Mac Lane surface form
    pub context: BoundedList<ContextItem>,
}

// --- Tactic Output Data Model ---

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum TacticResult {
    Success {
        patches: BoundedList<SemanticPatch>,
        alternatives: BoundedList<SemanticPatch>,
        ui_metadata: Option<UIMetadata>,
    },
    Failure {
        reason: TacticFailureReason,
        message: String,
        // In a real LSP context, this would be an actual lsp_types::Diagnostic
        diagnostic: Option<String>,
    },
    InProgress {
        message: String,
        progress_token: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum TacticFailureReason {
    InputMismatch,
    ContextMismatch,
    FuelExhausted,
    InternalError,
    SoundnessCheckFailed,
    NoAlternativeFound,
    // ...
}

// --- Minimal Tactic Runner ---

/// A minimal tactic runner that executes a tactic function.
/// In a real system, this would involve more complex state management
/// and interaction with the elaborator and Stonewall.
pub fn run_tactic<F>(input: TacticInput, tactic_fn: F) -> TacticResult
where
    F: Fn(TacticInput) -> TacticResult,
{
    // This function simulates the orchestration of a tactic call.
    // The actual "Stonewall" check would happen *after* a tactic
    // produced a SemanticPatch, by the EdgeLorD server.
    // For this starter slice, the tactic_fn directly produces the result.
    tactic_fn(input)
}

// --- Placeholder Tactic Functions (DSL represented as Rust functions) ---

/// Implements `intro.binder` logic.
/// Creates a SemanticPatch to introduce a binder.
pub fn intro_binder_tactic(input: TacticInput) -> TacticResult {
    let target_anchor = input
        .target_hole_id
        .map(|id| {
            StableAnchor::test(
                crate::refute::types::AnchorKind::Hole,
                "test_file",
                vec![], // owner_path
                id.parse().unwrap_or(0),
                0, // span_fingerprint
            )
        })
        .or_else(|| {
            input.target_goal_id.map(|id| {
                StableAnchor::test(
                    crate::refute::types::AnchorKind::Goal,
                    "test_file",
                    vec![], // owner_path
                    id.parse().unwrap_or(0),
                    0, // span_fingerprint
                )
            })
        })
        .unwrap_or_else(|| input.current_proof_state.current_focus_anchor.clone());

    let new_binder_name = input
        .additional_args
        .get("name")
        .cloned()
        .unwrap_or_else(|| "x".to_string());
    let new_binder_type = input
        .additional_args
        .get("type")
        .cloned()
        .unwrap_or_else(|| "Prop".to_string());

    let patch_kind = PatchKind::IntroBinding {
        name: new_binder_name.clone(),
        type_expr: new_binder_type,
    };

    // Example Mac Lane syntax for the new form. This string would be parsed
    // by the actual elaborator.
    let new_form_text = format!("(touch {} (hole {}))", new_binder_name, new_binder_name);

    let changes = BoundedList::from_vec(vec![SemanticChange::InsertForm {
        parent_anchor: target_anchor.clone(),
        position: InsertPosition::Prepend,
        new_form_text,
    }]);

    let mut patch = SemanticPatch {
        id: HashValue::zero(), // Will be computed
        version: 1,
        kind: patch_kind,
        target_anchor,
        changes,
        new_subgoals: BoundedList::empty(),
        ui_metadata: Some(UIMetadata {
            title: format!("Intro binder `{}`", new_binder_name),
            description: Some("Introduces a new binder into the context.".to_string()),
            icon: None,
        }),
        soundness_proof_artifact: None,
    };
    patch.id = patch.compute_id();

    TacticResult::Success {
        patches: BoundedList::from_vec(vec![patch]),
        alternatives: BoundedList::empty(),
        ui_metadata: None,
    }
}

/// Implements `exact.term` logic.
/// Creates a SemanticPatch to fill a hole with a given term.
pub fn exact_term_tactic(input: TacticInput) -> TacticResult {
    let hole_id = match input.target_hole_id {
        Some(id) => id,
        None => {
            return TacticResult::Failure {
                reason: TacticFailureReason::InputMismatch,
                message: "exact.term requires a target hole ID".to_string(),
                diagnostic: None,
            }
        }
    };

    let term = match input.additional_args.get("term") {
        Some(t) => t.clone(),
        None => {
            return TacticResult::Failure {
                reason: TacticFailureReason::InputMismatch,
                message: "exact.term requires a 'term' argument".to_string(),
                diagnostic: None,
            }
        }
    };

    // In a real system, we would check if the term's type matches the hole's expected type
    // and if the term is well-formed using the Mac Lane elaborator. For this stub,
    // we assume the term is valid.

    let target_anchor = StableAnchor::test(
        crate::refute::types::AnchorKind::Hole,
        "test_file",
        vec![], // owner_path
        hole_id.parse().unwrap_or(0),
        0, // span_fingerprint
    );

    let patch_kind = PatchKind::FillHole {
        hole_id: hole_id.clone(),
        term: term.clone(),
    };

    let changes = BoundedList::from_vec(vec![SemanticChange::UpdateForm {
        target_anchor: target_anchor.clone(),
        new_form_text: term,
    }]);

    let mut patch = SemanticPatch {
        id: HashValue::zero(),
        version: 1,
        kind: patch_kind,
        target_anchor,
        changes,
        new_subgoals: BoundedList::empty(),
        ui_metadata: Some(UIMetadata {
            title: format!("Fill hole `{}` with term", hole_id),
            description: Some("Fills the specified hole with the given term.".to_string()),
            icon: None,
        }),
        soundness_proof_artifact: None,
    };
    patch.id = patch.compute_id();

    TacticResult::Success {
        patches: BoundedList::from_vec(vec![patch]),
        alternatives: BoundedList::empty(),
        ui_metadata: None,
    }
}

/// Implements `rewrite.rule` logic.
/// Creates a SemanticPatch to apply a rewrite rule.
pub fn rewrite_rule_tactic(input: TacticInput) -> TacticResult {
    let rule_id = match input.additional_args.get("rule_id") {
        Some(id) => id.clone(),
        None => {
            return TacticResult::Failure {
                reason: TacticFailureReason::InputMismatch,
                message: "rewrite.rule requires a 'rule_id' argument".to_string(),
                diagnostic: None,
            }
        }
    };

    let direction_str = input
        .additional_args
        .get("direction")
        .cloned()
        .unwrap_or_else(|| "LeftToRight".to_string());
    let direction = match direction_str.as_str() {
        "LeftToRight" => RewriteDirection::LeftToRight,
        "RightToLeft" => RewriteDirection::RightToLeft,
        "Bidirectional" => RewriteDirection::Bidirectional,
        _ => {
            return TacticResult::Failure {
                reason: TacticFailureReason::InputMismatch,
                message: format!("Invalid rewrite direction: {}", direction_str),
                diagnostic: None,
            }
        }
    };

    let target_span = input
        .additional_args
        .get("target_span_start")
        .and_then(|s_start| s_start.parse::<usize>().ok())
        .and_then(|start| {
            input
                .additional_args
                .get("target_span_end")
                .and_then(|s_end| s_end.parse::<usize>().ok())
                .map(|end| ByteSpan::new(start, end))
        })
        .unwrap_or(ByteSpan::new(0, 0)); // Default to (0,0) if no span provided

    let target_anchor = input
        .target_goal_id
        .map(|id| {
            StableAnchor::test(
                crate::refute::types::AnchorKind::Goal,
                "test_file",
                vec![], // owner_path
                id.parse().unwrap_or(0),
                0, // span_fingerprint
            )
        })
        .unwrap_or_else(|| input.current_proof_state.current_focus_anchor.clone());

    // Simulate rewriting. In a real system, this would involve AST traversal
    // and application of the rewrite rule. For this stub, we'll just
    // generate a placeholder semantic change. The new_form_text would be
    // the result of the rewrite.
    let new_form_text = format!("(rewritten_form_by_{})", rule_id); // Placeholder

    let patch_kind = PatchKind::Rewrite {
        rule_id: rule_id.clone(),
        direction,
        target_span,
    };

    let changes = BoundedList::from_vec(vec![SemanticChange::UpdateForm {
        target_anchor: target_anchor.clone(),
        new_form_text,
    }]);

    let mut patch = SemanticPatch {
        id: HashValue::zero(),
        version: 1,
        kind: patch_kind,
        target_anchor,
        changes,
        new_subgoals: BoundedList::empty(),
        ui_metadata: Some(UIMetadata {
            title: format!("Rewrite with `{}`", rule_id),
            description: Some("Applies a named rewrite rule.".to_string()),
            icon: None,
        }),
        soundness_proof_artifact: None,
    };
    patch.id = patch.compute_id();

    TacticResult::Success {
        patches: BoundedList::from_vec(vec![patch]),
        alternatives: BoundedList::empty(),
        ui_metadata: None,
    }
}

/// Implements `simp.fuel` logic (simplified).
/// Creates a SemanticPatch representing a simplification, or fails if fuel is exhausted.
pub fn simp_fuel_tactic(input: TacticInput) -> TacticResult {
    let fuel_str = input
        .additional_args
        .get("fuel")
        .cloned()
        .unwrap_or_else(|| "10".to_string());
    let fuel: u32 = match fuel_str.parse() {
        Ok(f) => f,
        Err(_) => {
            return TacticResult::Failure {
                reason: TacticFailureReason::InputMismatch,
                message: "simp.fuel requires a valid integer 'fuel' argument".to_string(),
                diagnostic: None,
            }
        }
    };

    if fuel == 0 {
        return TacticResult::Failure {
            reason: TacticFailureReason::FuelExhausted,
            message: "Fuel exhausted before any simplification could occur".to_string(),
            diagnostic: None,
        };
    }

    let target_anchor = input
        .target_goal_id
        .map(|id| {
            StableAnchor::test(
                crate::refute::types::AnchorKind::Goal,
                "test_file",
                vec![], // owner_path
                id.parse().unwrap_or(0),
                0, // span_fingerprint
            )
        })
        .unwrap_or_else(|| input.current_proof_state.current_focus_anchor.clone());

    // Simulate simplification up to fuel limit.
    // For this stub, we'll just indicate a single simplification step occurred.
    // The new_form_text would be the result of the simplification.
    let new_form_text = format!("(simplified_form_fuel_{})", fuel);

    // Re-using Rewrite PatchKind for simplification for simplicity in this stub.
    // A dedicated Simp PatchKind could be introduced later.
    let patch_kind = PatchKind::Rewrite {
        rule_id: format!("simp_fuel_step_{}", fuel),
        direction: RewriteDirection::Bidirectional,
        target_span: ByteSpan::new(0, 0), // Placeholder for the actual simplified span
    };

    let changes = BoundedList::from_vec(vec![SemanticChange::UpdateForm {
        target_anchor: target_anchor.clone(),
        new_form_text,
    }]);

    let mut patch = SemanticPatch {
        id: HashValue::zero(),
        version: 1,
        kind: patch_kind,
        target_anchor,
        changes,
        new_subgoals: BoundedList::empty(),
        ui_metadata: Some(UIMetadata {
            title: format!("Simplify (fuel: {})", fuel),
            description: Some(format!("Applies simplification with a fuel limit of {}.", fuel)),
            icon: None,
        }),
        soundness_proof_artifact: None,
    };
    patch.id = patch.compute_id();

    TacticResult::Success {
        patches: BoundedList::from_vec(vec![patch]),
        alternatives: BoundedList::empty(),
        ui_metadata: None,
    }
}